apiVersion: v1
kind: Service
metadata:
  name: {{ template "keycloak.fullname" . }}-headless
  {{- if .Values.keycloak.namespace }}
  namespace: {{ .Values.keycloak.namespace }}
  {{- end}}
  labels:
    app: {{ template "keycloak.name" . }}
    chart: {{ template "keycloak.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.keycloak.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app: {{ template "keycloak.name" . }}
    release: "{{ .Release.Name }}"
